name: Update Metrics

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get most played songs on Apple Music
        uses: lowlighter/metrics@latest
        with:
          filename: replay_2022.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: https://embed.music.apple.com/br/playlist/replay-2022/pl.rp-kDDGHwAoLGEl
          plugin_music_limit: 4
